app = "chess-web"
primary_region = "den"

[deploy]
strategy = "rolling"

[http_service]
internal_port = 8080
auto_stop_machines = "stop"
auto_start_machines = true
[http_service.concurrency]
type = "requests"
soft_limit = 50
hard_limit = 100

[[vm]]
size = "shared-cpu-1x"
memory = "1GB"
cpus = 1

[env]
GOMAXPROCS = "1"
GOMEMLIMIT = "800000000"
